### ISSUE TITLE
Question - does it maintain the relationship between a federated model and it's links

### ISSUE THREAD

**Issue by jmcouffin** [autodesk-platform-services/aps-hubs-bulk-files-manager#1]
Hi, 
For Revit files,
Does it maintain the relationship between a federated model and it's links?
Do we have to relink / repath all links afterwards?

I guess Yes, but I wanted to get a confirmation

**Comment by xiaodongliang** [comment]
Hi @jmcouffin , if you meant by [Upload Linked Files] of ACC/BIM360, yes, this sample does not handle it, but as long as the files have been linked by the way of  [Upload Linked Files], the references info is stored. When they are uploaded back to ACC/BIM360, they referenced are still there.

if you meant by source files (never been uploaded to ACC/BIM360 before) , you will need to setup the reference by yourself. see this blog: https://aps.autodesk.com/blog/bim360-docs-setting-external-references-between-files-upload-linked-files
